### ISSUE TITLE
edición secciones

### ISSUE THREAD

**Issue by jciturras** [isa-rc42/webRC42ISA#1]
- events
- projects
- publications
- links
- about: board, members and past members (destacados?), past presidents

**Comment by juancarloscastillo** [comment]
@jciturras , recuerda que lo del board es simplemente un listado con fotos, no se requiere página aparte de cada miembro del board, menos de los miembros, habiamos visto esto: https://realworlddatascience.net/viewpoints/editors-blog/posts/2022/10/18/meet-the-team.html

**Comment by juancarloscastillo** [comment]
Y porfa, incluir los nombres del board actual, no mas Webers

**Comment by juancarloscastillo** [comment]
Están en la página de ISA https://www.isa-sociology.org/en/research-networks/research-committees/rc42-social-psychology
